# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Flickr_PF_ImageGallery' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flickr_PF_ImageGallery

end
