# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'Flickr_PF_ImageGallery' do
  use_frameworks!

pod 'Alamofire', '~> 4.5'
  # Pods for Flickr_PF_ImageGallery

end
